AUX_P = aux
LUAC_T= bin/luac
LUAC2C_T= bin/luac2c
LUA_O= aux/one.o
LUA_A= aux/liblua.a
LUA_T= bin/lua
ONE= $(AUX_P)/one
LUACFLAGS?= -s
ECHO = @printf '%s\n'
ECHON = @printf '%s'
ECHOT = @printf ' %s\t%s\n'
M4 = m4
STRIP = strip
STRIPFLAGS= --strip-all
RM= rm
RMFLAGS= -f
RMRF= rm -rf

_rest= $(wordlist 2,$(words $(1)),$(1))
_lget= $(firstword lib/$(1))/Makefile $(if $(_rest),$(call _lget,$(_rest)),)
_vget= $(firstword vendor/$(1))/Makefile $(if $(_rest),$(call _vget,$(_rest)),)
SRC_P= vendor/lua
INCLUDES:= -I$(SRC_P) -Iinclude -I$(AUX_P)
CLUA_MODS+= $(foreach m, $(VENDOR_C), -Lvendor/$m -l$m)
LUA_MODS+= $(foreach m, $(VENDOR_LUA), vendor/$m/$m.lua)
BUILD_DEPS = has-$(CC) has-$(RANLIB) has-$(LD) has-$(AR) has-$(M4) has-$(STRIP) has-$(RM)
